import { Exercise } from '../types'

export const EXERCISES: Exercise[] = [
  // Kettlebell
  {
    id: 'kb_swing',
    name: 'KB Swings',
    category: 'kettlebell',
    unit: 'weight_reps',
    defaultWeight: 16,
    defaultReps: 15,
    defaultSets: 4,
    weightIncrement: 2,
    description: 'Hip hinge drive — keep back flat, power from glutes',
  },
  {
    id: 'kb_goblet_squat',
    name: 'KB Goblet Squat',
    category: 'kettlebell',
    unit: 'weight_reps',
    defaultWeight: 16,
    defaultReps: 12,
    defaultSets: 3,
    weightIncrement: 2,
    description: 'Hold KB at chest, squat deep, elbows inside knees',
  },
  {
    id: 'kb_clean_press_l',
    name: 'KB Clean & Press (Left)',
    category: 'kettlebell',
    unit: 'weight_reps',
    defaultWeight: 12,
    defaultReps: 8,
    defaultSets: 3,
    weightIncrement: 2,
    description: 'Clean to rack, press overhead, lower under control',
  },
  {
    id: 'kb_clean_press_r',
    name: 'KB Clean & Press (Right)',
    category: 'kettlebell',
    unit: 'weight_reps',
    defaultWeight: 12,
    defaultReps: 8,
    defaultSets: 3,
    weightIncrement: 2,
    description: 'Clean to rack, press overhead, lower under control',
  },
  {
    id: 'kb_deadlift',
    name: 'KB Deadlift',
    category: 'kettlebell',
    unit: 'weight_reps',
    defaultWeight: 24,
    defaultReps: 10,
    defaultSets: 4,
    weightIncrement: 4,
    description: 'Hinge at hips, drive through heels, full hip extension at top',
  },
  {
    id: 'kb_row_l',
    name: 'KB Row (Left)',
    category: 'kettlebell',
    unit: 'weight_reps',
    defaultWeight: 16,
    defaultReps: 10,
    defaultSets: 3,
    weightIncrement: 2,
    description: 'Brace on bench or knee, pull elbow back, squeeze at top',
  },
  {
    id: 'kb_row_r',
    name: 'KB Row (Right)',
    category: 'kettlebell',
    unit: 'weight_reps',
    defaultWeight: 16,
    defaultReps: 10,
    defaultSets: 3,
    weightIncrement: 2,
    description: 'Brace on bench or knee, pull elbow back, squeeze at top',
  },
  {
    id: 'kb_shoulder_press_l',
    name: 'KB Shoulder Press (Left)',
    category: 'kettlebell',
    unit: 'weight_reps',
    defaultWeight: 12,
    defaultReps: 8,
    defaultSets: 3,
    weightIncrement: 2,
    description: 'Press straight overhead, core tight, avoid side-lean',
  },
  {
    id: 'kb_shoulder_press_r',
    name: 'KB Shoulder Press (Right)',
    category: 'kettlebell',
    unit: 'weight_reps',
    defaultWeight: 12,
    defaultReps: 8,
    defaultSets: 3,
    weightIncrement: 2,
    description: 'Press straight overhead, core tight, avoid side-lean',
  },
  {
    id: 'kb_russian_twist',
    name: 'Russian Twists (KB)',
    category: 'kettlebell',
    unit: 'weight_reps',
    defaultWeight: 12,
    defaultReps: 20,
    defaultSets: 3,
    weightIncrement: 2,
    description: 'Lean back 45°, rotate KB side to side, feet off ground',
  },
  // Cardio
  {
    id: 'treadmill',
    name: 'Treadmill',
    category: 'cardio',
    unit: 'distance_duration',
    defaultDuration: 1500, // 25 min
    defaultDistance: 1.5,
    defaultSets: 1,
    description: 'Interval: 2 min fast / 1 min walk, or steady 3.5 mph incline',
  },
  {
    id: 'elliptical',
    name: 'Elliptical',
    category: 'cardio',
    unit: 'duration',
    defaultDuration: 900, // 15 min
    defaultSets: 1,
    description: 'Resistance 8-10, push/pull with arms, steady pace',
  },
  // Bodyweight
  {
    id: 'dips',
    name: 'Dips',
    category: 'dips',
    unit: 'reps_only',
    defaultReps: 10,
    defaultSets: 3,
    description: 'Lean slightly forward for chest focus, full range of motion',
  },
  {
    id: 'pushups',
    name: 'Push-ups',
    category: 'bodyweight',
    unit: 'reps_only',
    defaultReps: 15,
    defaultSets: 3,
    description: 'Hands shoulder-width, body straight, chest to floor',
  },
  {
    id: 'bw_squat',
    name: 'Bodyweight Squats',
    category: 'bodyweight',
    unit: 'reps_only',
    defaultReps: 20,
    defaultSets: 3,
    description: 'Feet shoulder-width, squat below parallel, drive through heels',
  },
  {
    id: 'walking_lunges',
    name: 'Walking Lunges',
    category: 'bodyweight',
    unit: 'reps_only',
    defaultReps: 12,
    defaultSets: 3,
    description: '12 reps per leg, long stride, back knee near floor',
  },
  {
    id: 'mountain_climbers',
    name: 'Mountain Climbers',
    category: 'bodyweight',
    unit: 'duration',
    defaultDuration: 30,
    defaultSets: 3,
    description: 'High plank, drive knees to chest alternating, fast pace',
  },
  {
    id: 'burpees',
    name: 'Burpees',
    category: 'bodyweight',
    unit: 'reps_only',
    defaultReps: 10,
    defaultSets: 3,
    description: 'Drop to push-up, jump feet in, jump up with arms overhead',
  },
  {
    id: 'plank',
    name: 'Plank',
    category: 'bodyweight',
    unit: 'duration',
    defaultDuration: 45,
    defaultSets: 3,
    description: 'Forearms or hands, hips level, squeeze abs and glutes',
  },
]

export const exerciseMap = Object.fromEntries(EXERCISES.map(e => [e.id, e]))
